export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_RESPONSE = "SET_RESPONSE";
export const SET_TOKEN = "SET_TOKEN";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";

export const GET_ROLES = "GET_ROLES";
export const CREATE_ROLE = "CREATE_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const ASSIGN_ROLE = "ASSIGN_ROLE";
export const GET_USERS = "GET_USERS";

export const CREATING_ROLE = "CREATING_ROLE";
export const UPDATING_ROLE = "UPDATING_ROLE";
export const DELETING_ROLE = "DELETING_ROLE";
export const ASSIGNING_ROLE = "ASSIGNING_ROLE";
export const SET_RESOLVED = "SET_RESOLVED";

export const SET_SUCCESS = "SET_SUCCESS";
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_REQUESTS_ERROR = "GET_REQUESTS_ERROR";
export const SET_FORGOT_LOADING = "SET_FORGOT_LOADING";
export const SET_FORGOT_ERROR = "SET_FORGOT_ERROR";
export const SET_FORGOT_SUCCESS = "SET_FORGOT_SUCCESS";
export const SET_RESET_INVALID = "SET_RESET_INVALID";
export const SET_RESET_ERROR = "SET_RESET_ERROR";
export const SET_RESET_SUCCESS = "SET_RESET_SUCCESS";
export const SET_RESET_LOADING = "SET_RESET_LOADING";

export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR";
export const CREATE_ACCOMMODATION = "CREATE_ACCOMMODATION";
export const SET_ACCOMMODATIONS_ERROR = "SET_ACCOMMODATIONS_ERROR";
export const GET_ACCOMMODATIONS = "GET_ACCOMMODATIONS";
export const GET_ACCOMMODATIONS_ERROR = "GET_ACCOMMODATIONS_ERROR";
export const DELETE_ACCOMMODATION = "DELETE_ACCOMMODATION";
export const DELETE_ACCOMMODATION_ERROR = "DELETE_ACCOMMODATION_ERROR";

export const UPDATE_ACCOMMODATION_ERROR = "UPDATE_ACCOMMODATION_ERROR";
export const UPDATE_ACCOMMODATION = "UPDATE_ACCOMMODATION";
