export const types = {
  GET_PROFILE: 'GET_PROFILE',
  COMPLETE_PROFILE: 'COMPLETE_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_ERRORS: 'GET_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  GET_MANAGER: 'GET_MANAGER',
};
