export const types = {
  FETCH_REQUESTS_SUCCESS: "FETCH_REQUESTS_SUCCESS",
  FETCH_REQUESTS_ERROR: "FETCH_REQUESTS_ERROR",
  FETCH_REQUEST_SUCCESS: "FETCH_REQUEST_SUCCESS",
  FETCH_REQUEST_ERROR: "FETCH_REQUEST_ERROR",
};
